import assert from 'node:assert/strict';
import * as THREE from '../dist/three.module.js';
import {BatController} from '../dist/input.js';
import {SHOT_MOTIONS,sampleMotion,canBlend} from '../dist/realism/ShotMotionLibrary.js';
import {PlayerBody,buildWillowBat} from '../dist/realism/PlayerBody.js';
import {batBasis,batWorldPoint,batPointVelocity,v,length,sub} from '../dist/physics.js';
let count=0;const test=(n,f)=>{f();count++;console.log('PASS '+n);};
function stroke(id,hand='right',impact=false){const c=new BatController();c.hand=hand;c.reset();c.poseController.shot=id;c.step(.001);c.swing(.7);const poses=[];for(let i=0;i<1400;i++){if(impact&&i===380)c.poseController.impact({region:'toe',twistImpulse:1});poses.push(c.step(.001));}return poses;}
test('every named shot owns separate human channels',()=>{const ids=Object.keys(SHOT_MOTIONS);assert.equal(ids.length,19);for(const id of ids){const p=SHOT_MOTIONS[id];for(const key of ['headPath','leadShoulderCurve','trailShoulderCurve','leadElbowCurve','trailElbowCurve','topHandSpline','bottomHandSpline','wristCurve','batHeadPath'])assert.ok(p[key].length>=7);for(const other of ids.filter(x=>x!==id))assert.notEqual(p.topHandSpline,SHOT_MOTIONS[other].topHandSpline);}});
test('shot families differ in geometry, not only target yaw',()=>{const at=id=>sampleMotion(id,SHOT_MOTIONS[id].contactPhase);assert.ok(at('cover').frontFoot.x-at('straight').frontFoot.x>.2);assert.ok(at('sweep').head.y<-.4);assert.ok(at('pull').thorax<-.5);assert.ok(at('cut').orientation.z< -1);assert.ok(Math.abs(at('straight').orientation.z)<.05);assert.ok(at('backdefence').backFoot.z>.95);assert.ok(at('hook').top.y-at('pull').top.y>.15);assert.ok(at('latecut').top.z-at('cut').top.z>.2);});
test('defence has a hold; flick wrist closure is late',()=>{const p=SHOT_MOTIONS.defence;assert.ok(length(sub(sampleMotion('defence',p.t||.43).top,sampleMotion('defence',.65).top))<.035);assert.equal(sampleMotion('flick',.33).wrist,0);assert.ok(sampleMotion('flick',.64).wrist>.3);});
test('only explicitly related motion pairs can blend',()=>{assert.ok(canBlend('cut','latecut'));assert.ok(canBlend('straight','ondrive'));assert.equal(canBlend('straight','pull'),false);assert.equal(canBlend('cover','sweep'),false);});
test('all profiles keep a rigid two-hand grip and exact collision velocity',()=>{for(const id of Object.keys(SHOT_MOTIONS))for(const hand of ['right','left']){const poses=stroke(id,hand);for(let i=1;i<poses.length;i++){const p=poses[i],a=batBasis(p.yaw,p.loft,p.roll,p.twist);assert.ok(Math.abs(length(sub(p.trails.topHand,p.trails.bottomHand))-.095)<1e-9);assert.ok(length(sub(batWorldPoint(v(0,.5,0),p),p.handPivot))<1e-9);assert.ok(Number.isFinite(p.kinematics.batHeadSpeed));assert.ok(p.kinematics.batHeadSpeed<45,id+' velocity '+p.kinematics.batHeadSpeed);assert.ok(length(sub(batPointVelocity(v(0,-.07,0),poses[i-1],p),p.kinematics.batHeadVelocity))<1e-8);}}});
test('head stays level and arm lengths stay fixed across difficult shots',()=>{const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(),body=new PlayerBody(scene,camera,buildWillowBat());for(const id of ['cover','pull','hook','sweep'])for(const hand of ['right','left']){const poses=stroke(id,hand);for(let i=0;i<poses.length;i+=10){const p=poses[i];body.update(p,i*.001,.15,hand);body.setLook(.15,-.2);const eye=camera.getWorldPosition(new THREE.Vector3());assert.ok(eye.distanceTo(new THREE.Vector3(p.trails.head.x,p.trails.head.y,p.trails.head.z))<1e-7);const q=camera.getWorldQuaternion(new THREE.Quaternion());assert.ok(q.angleTo(new THREE.Quaternion().setFromEuler(new THREE.Euler(-.2,.15,0,'YXZ')))<1e-6);for(const arm of body.arms){assert.ok(Math.abs(arm.upper.scale.y-.37)<1e-6,id+' upper arm '+arm.upper.scale.y);assert.ok(Math.abs(arm.lower.scale.y-.39)<1e-6,id+' lower arm '+arm.lower.scale.y);}}}});
test('impact alters follow-through and a miss does not',()=>{const clean=stroke('straight'),toe=stroke('straight','right',true);assert.ok(Math.abs(clean[450].motion.phase-toe[450].motion.phase)>.001);assert.ok(Math.abs(toe[400].twist)>0);});
test('an unsuitable ball does not pull a drive up to bouncer height',()=>{const c=new BatController();c.poseController.shot='straight';c.poseController.observe(v(.6,1.8,-2),v(0,2,30));c.swing(.7);let maxContactHeight=0;for(let i=0;i<600;i++){const p=c.step(.001);if(Math.abs(p.motion.phase-.49)<.03)maxContactHeight=Math.max(maxContactHeight,p.trails.sweetSpot.y);}assert.ok(maxContactHeight<1.1);});
console.log(count+' shot-motion checks passed');
