import assert from 'node:assert/strict';
import fs from 'node:fs';
import {pathToFileURL} from 'node:url';
import {BallSimulation,makeIntent,makeRelease,v,STEP,sweepBat,Ledger,replayInputs,PROFILES} from '../dist/physics.js';
import {BatController} from '../dist/input.js';
let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name);}
const base={position:v(0,2,-18),velocity:v(0,-3,34),spin:v(),seamNormal:v(1,0,0),seamCoefficient:0};
test('gravity agrees with analytic trajectory without aerodynamics',()=>{const s=new BallSimulation(base,{physics:{drag:0,spinLift:0}});for(let i=0;i<100;i++)s.step();assert.ok(Math.abs(s.position.y-(2-3*.1-.5*9.81*.1**2))<.0006);assert.ok(Math.abs(s.position.z-(-18+34*.1))<1e-10);});
test('drag reduces speed without gravity or side forces',()=>{const s=new BallSimulation(base,{physics:{gravity:0,spinLift:0}});for(let i=0;i<100;i++)s.step();assert.ok(s.velocity.z<34);});
test('render rates do not affect fixed-step authority',()=>{function run(hz){const s=new BallSimulation(base);let a=0;for(let frame=0;frame<hz;frame++){a+=1/hz;while(a+1e-12>=STEP){s.step();a-=STEP;}}return JSON.stringify([s.position,s.velocity,s.events]);}assert.equal(run(30),run(60));assert.equal(run(60),run(120));assert.equal(run(120),run(240));});
test('swept contact detects crossing thin bat face',()=>{const b={position:v(0,.7,0),yaw:0,loft:0};assert.ok(sweepBat(v(0,.7,-.2),v(0,.7,.2),b,b,.0361));assert.equal(sweepBat(v(.3,.7,-.2),v(.3,.7,.2),b,b,.0361),null);});
test('physical collision reverses ball; wrong line misses',()=>{const release={...base,position:v(0,.7,-.2),velocity:v(0,0,36)};let s=new BallSimulation(release,{physics:{gravity:0}});for(let i=0;i<20;i++)s.step({position:v(0,.7,0),yaw:0,loft:0});assert.ok(s.contact);assert.ok(s.velocity.z<0);s=new BallSimulation(release,{physics:{gravity:0}});for(let i=0;i<20;i++)s.step({position:v(.5,.7,0),yaw:0,loft:0});assert.equal(s.contact,null);});
test('left and right control defaults mirror guard; leave bypasses contact',()=>{const c=new BatController();c.hand='left';c.reset();assert.equal(c.target.x,-.15);const s=new BallSimulation({...base,position:v(0,.7,-.2),velocity:v(0,0,36)},{physics:{gravity:0}});for(let i=0;i<20;i++)s.step({position:v(0,.7,0),yaw:0,loft:0,leave:true});assert.equal(s.contact,null);});
test('surface restitution changes the bounce',()=>{const release={...base,position:v(0,.05,-5),velocity:v(0,-5,20)};const a=new BallSimulation(release,{pitch:PROFILES.hard}),b=new BallSimulation(release,{pitch:PROFILES.soft});for(let i=0;i<5;i++){a.step();b.step();}assert.ok(a.velocity.y>b.velocity.y);});
test('rules separate delivery count, legal balls, no-balls and wides',()=>{const l=new Ledger();l.commit(1,[{type:'WideDetected'}]);l.commit(2,[{type:'NoBallDetected'},{type:'WicketBroken'}]);l.commit(3,[{type:'BatContact'}]);assert.equal(l.deliveries,3);assert.equal(l.legalBalls,1);assert.equal(l.wickets,0);assert.equal(l.contacts,1);assert.equal(l.commit(3,[]),false);});
test('recorded bat inputs reproduce exact ball and contact events',()=>{const s=new BallSimulation({...base,position:v(0,.7,-.2),velocity:v(0,0,36)});const b={position:v(0,.7,0),yaw:0,loft:0};s.inputs.push({tick:1,bat:b});while(!s.dead)s.step(b);const replay=replayInputs(s.export());assert.deepEqual(replay.position,s.position);assert.deepEqual(replay.contact,s.contact);assert.deepEqual(replay.events,s.events);});
test('mouse motion swings without a pressed button',()=>{const c=new BatController();c.move(10,-30,.02);assert.ok(c.stroke);assert.ok(c.target.x>.15);});
test('trackpad units, inversion, pinch exclusion and momentum guard',()=>{const c=new BatController();c.mode='trackpad';let prevented=0;const event=(dy,extra={})=>({deltaX:0,deltaY:dy,deltaMode:0,preventDefault(){prevented++;},...extra});c.wheel(event(-18),100);assert.ok(c.stroke);const stroke=c.lastStroke;c.step(.4);c.wheel(event(-8),130);c.wheel(event(-3),160);assert.equal(c.lastStroke,stroke);assert.equal(c.wheel(event(-50,{ctrlKey:true}),200),false);assert.equal(prevented,3);c.reset();c.invert=true;c.wheel(event(1,{deltaMode:1}),500);assert.ok(c.stroke);});
test('invalid regulation mass is rejected',()=>assert.throws(()=>new BallSimulation(base,{physics:{mass:.2}}),RangeError));
// Full application smoke test with the actual Three.js scene and a renderer stub.
const elements=new Map(),handlers={};let loop,read;globalThis.innerWidth=1366;globalThis.innerHeight=768;globalThis.devicePixelRatio=1;globalThis.addEventListener=()=>{};globalThis.requestAnimationFrame=fn=>loop=fn;globalThis.RendererStub=class{shadowMap={};setPixelRatio(){}setSize(){}render(){}};
function el(id){if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',value:({inputMode:'mouse',sensitivity:'1',hand:'right',surface:'hard'})[id]||'',checked:false,listeners:{},classList:{add(){},remove(){}},addEventListener(n,f){this.listeners[n]=f;},showModal(){this.open=true;},close(){this.open=false;this.listeners.close?.();},setPointerCapture(){}});return elements.get(id);}
globalThis.document={getElementById:el,addEventListener:(n,f)=>handlers[n]=f,modelContext:{registerTool:t=>read=t.execute}};
function absoluteImports(source){return source.replace(/from '(\.\/[^']+)'/g,(_,p)=>'from '+JSON.stringify(pathToFileURL(process.cwd()+'/dist/'+p.slice(2)).href));}
let source=absoluteImports(fs.readFileSync('dist/game.js','utf8')).replace('new THREE.WebGLRenderer','new globalThis.RendererStub');await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));let clock=performance.now();function advance(seconds){for(let i=0;i<Math.ceil(seconds*100);i++){clock+=10;loop(clock);}}
test('whole scene starts, pauses, finishes, reviews and starts next ball',()=>{el('play').onclick();assert.equal(read().state,'runup');advance(.1);el('pause').onclick();const frozen=read();advance(1);assert.deepEqual(read(),frozen);el('pause').onclick();advance(15);assert.equal(read().state,'result');assert.equal(read().deliveries,1);el('replay').onclick();advance(.1);assert.equal(read().state,'replay');el('next').onclick();assert.equal(read().state,'runup');assert.equal(read().deliveries,1);});
console.log(`${passed} checks passed. WebGL drawing and physical input hardware not exercised.`);
